parameters:
- name: serviceConnection
  type: string
- name: hubServiceConnection
  type: string
- name: environmentType
  type: string
- name: vgs
  type: string
- name: resourceType
  type: string
- name: job
  type: string
- name: scope
  type: string
- name: jobDependsOn
  type: string
- name: location
  type: string
- name: spokeIndex
  type: string
  default: ''

jobs:
  - job: ${{parameters.job}}
    dependsOn: ${{parameters.jobDependsOn}}
    variables:
      - template: ${{parameters.vgs}} # contains the naming standard & global variables
        parameters:
          environmentType: ${{parameters.environmentType}} #environment override
          location: ${{parameters.location}} # environment override
          spokeIndex: ${{parameters.spokeIndex}} # Spoke numeric identifier
    steps: 
    - template: ../steps/get-subscriptions.yml
      parameters:
        serviceConnection: ${{parameters.serviceConnection}}
        hubServiceConnection: ${{parameters.hubServiceConnection}}
        environmentType: ${{parameters.environmentType}}

    - task: AzureCLI@2 # expressRoute
      displayName: Build ${{parameters.resourceType}} express Route
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: >
          az account set --subscription $(hubSubscriptionTask.hubSubscription) &&
          az deployment ${{parameters.scope}} create 
          --name "expressRoute"$(deployDate)
          --resource-group ${{variables.networkGroup}}
          --template-file Deployment/bicep-templates/${{parameters.resourceType}}/${{parameters.resourceType}}.bicep 
          --parameters Deployment/bicep-templates/${{parameters.resourceType}}/${{parameters.resourceType}}.${{variables.locationCode}}${{variables.spokePath}}.parameters.json
          #--parameters "eRCktNamePrefix="${{variables.eRCktNamePrefix}}
          #--parameters "networkGroup="${{variables.networkGroup}}

    - task: AzureCLI@2 # expressRoute
      displayName: Build ${{parameters.resourceType}} express Route private peering
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: >
          az account set --subscription $(hubSubscriptionTask.hubSubscription) &&
          az deployment ${{parameters.scope}} create 
          --name "expressRoute"$(deployDate)
          --resource-group ${{variables.networkGroup}}
          --template-file Deployment/bicep-templates/${{parameters.resourceType}}/${{parameters.resourceType}}-private-peering.bicep 
          --parameters Deployment/bicep-templates/${{parameters.resourceType}}/${{parameters.resourceType}}-private-peering.${{variables.locationCode}}${{variables.spokePath}}.parameters.json
          #--parameters "eRCktNamePrefix="${{variables.eRCktNamePrefix}}
          #--parameters "networkGroup="${{variables.networkGroup}}


# Example from developer computer
#az deployment group create `
#    --name "expressRoute" `
#    --resource-group rg-dev-ae-network `
#    --template-file Deployment/bicep-templates/expressRoute/expressRoute.bicep `
#    --parameters Deployment/bicep-templates/exoressRoute/expressRoute.ae.parameters.json `
#    --parameters eRCktNamePrefix="dns-dev-ae-"
#    --parameters networkGroup="rg-dev-ae-network"