parameters:
- name: serviceConnection
  type: string
- name: hubServiceConnection
  type: string
- name: environmentType
  type: string
- name: vgs
  type: string
- name: resourceType
  type: string
- name: job
  type: string
# - name: jobDependsOn
#   type: string
- name: scope
  type: string
- name: location
  type: string
- name: osType
  type: string  
- name: spokeIndex
  type: string
  default: ''

jobs:
  - job: ${{parameters.job}}
    # dependsOn: ${{parameters.jobDependsOn}}
    variables:
      - template: ${{parameters.vgs}} # contains the naming standard & global variables
        parameters:
          environmentType: ${{parameters.environmentType}} #environment override
          location: ${{parameters.location}} # environment override
          spokeIndex: ${{parameters.spokeIndex}} # Spoke numeric identifier
    steps: 
    - template: ../steps/get-subscriptions.yml
      parameters:
        serviceConnection: ${{parameters.serviceConnection}}
        hubServiceConnection: ${{parameters.hubServiceConnection}}
        environmentType: ${{parameters.environmentType}}

    - task: AzureCLI@2 # App Service Plan
      displayName: Create ${{parameters.resourceType}} Plan on ${{parameters.osType}}
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: >
          az account set --subscription $(hubSubscriptionTask.hubSubscription) &&
          az deployment ${{parameters.scope}} create 
          --name "appServicePlan"$(deployDate)
          --resource-group ${{variables.networkGroup}}
          --template-file Deployment/bicep-templates/${{parameters.resourceType}}/${{parameters.resourceType}}Plan.${{parameters.osType}}.bicep 
          --parameters Deployment/bicep-templates/${{parameters.resourceType}}/${{parameters.resourceType}}Plan.${{parameters.osType}}.${{variables.locationCode}}${{variables.spokePath}}.parameters.json
          --parameters "location="${{parameters.location}}
          --parameters "aspPrefix"=${{variables.aspPrefix}}


    - task: AzureCLI@2 # app service
      displayName: Create ${{parameters.resourceType}} on ${{parameters.osType}} 
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: >
          az account set --subscription $(hubSubscriptionTask.hubSubscription) &&
          az deployment ${{parameters.scope}} create 
          --name "appService"$(deployDate)
          --resource-group ${{variables.networkGroup}}
          --template-file Deployment/bicep-templates/${{parameters.resourceType}}/${{parameters.resourceType}}.${{parameters.osType}}.bicep 
          --parameters Deployment/bicep-templates/${{parameters.resourceType}}/${{parameters.resourceType}}.${{parameters.osType}}.${{variables.locationCode}}${{variables.spokePath}}.parameters.json
          --parameters "aspPrefix"=${{variables.aspPrefix}}
          --parameters "asPrefix"=${{variables.asPrefix}}
