parameters:
- name: environmentType
  type: string
- name: serviceConnection
  type: string
- name: hubServiceConnection
  type: string
- name: stageName
  type: string
stages:
  - stage: ${{parameters.stageName}}
    # do not run prod unless in master branch
    # only run if previous stage has completed successfully
    condition: and(or(not(eq('${{ parameters.environmentType }}', 'prod')), eq(variables['Build.SourceBranch'], 'refs/heads/master')),succeeded())
    jobs:
    # For Hub build the serviceConnection & hubServiceConnection are the same. This is not true for spoke

    # Resource Groups
      - template: ../jobs/deploy-resourceGroups.yml
        parameters:
          serviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: resourceGroups
          job: ${{parameters.stageName}}_RGs_AustraliaEast
          location: AustraliaEast
          scope: sub
      #- template: ../jobs/deploy-resourceGroups.yml
      #  parameters:
      #    serviceConnection: ${{parameters.serviceConnection}}
      #    environmentType: ${{parameters.environmentType}}
      #    vgs: ../vgs/global.yml
      #    resourceType: resourceGroups
      #    job: ${{parameters.stageName}}_RGs_AustraliaSouthEast
      #    location: AustraliaSouthEast
      #    scope: sub
      - template: ../jobs/deploy-actionGroups.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_RGs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: actionGroups
          job: ${{parameters.stageName}}_ActionGroups
          location: AustraliaEast
          scope: group

      # RoleAssignments
      # - template: ../jobs/deploy-roleAssignments.yml
      #   parameters:
      #     jobDependsOn: ${{parameters.stageName}}_RGs_AustraliaEast
      #     serviceConnection: ${{parameters.serviceConnection}}
      #     environmentType: ${{parameters.environmentType}}
      #     vgs: ../vgs/global.yml
      #     resourceType: roleAssignments
      #     job: ${{parameters.stageName}}_RoleAssignments_AustraliaEast
      #     location: AustraliaEast
      #     scope: group 
      # - template: ../jobs/deploy-roleAssignments.yml
      #   parameters:
      #     jobDependsOn: ${{parameters.stageName}}_RGs_AustraliaEast
      #     serviceConnection: ${{parameters.serviceConnection}}
      #     environmentType: ${{parameters.environmentType}}
      #     vgs: ../vgs/global.yml
      #     resourceType: roleAssignments
      #     job: ${{parameters.stageName}}_RoleAssignments_AustraliaSouthEast
      #     location: AustraliaSouthEast
      #     scope: group 
      
      # # Log Analytics
      - template: ../jobs/deploy-logAnalytics.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_RGs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: logAnalytics
          job: ${{parameters.stageName}}_WSs_AustraliaEast
          location: AustraliaEast
          scope: group

#       # # Data Collection Rule
      - template: ../jobs/deploy-dataCollectionRules.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_WSs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: dataCollectionRules
          job: ${{parameters.stageName}}_dataCollectionRules_AustraliaEast
          location: AustraliaEast
          scope: group 

      # #Storage Accounts
      - template: ../jobs/deploy-storageAccounts.yml 
        parameters:
          jobDependsOn: ${{parameters.stageName}}_WSs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: storageAccounts
          job: ${{parameters.stageName}}_SAs_AustraliaEast
          location: AustraliaEast
          scope: group
      #- template: ../jobs/deploy-storageAccounts.yml 
      #  parameters:
      #    jobDependsOn: ${{parameters.stageName}}_SAs_AustraliaEast
      #    serviceConnection: ${{parameters.serviceConnection}}
      #    hubserviceConnection: ${{parameters.serviceConnection}}
      #    environmentType: ${{parameters.environmentType}}
      #    vgs: ../vgs/global.yml
      #    resourceType: storageAccounts
      #    job: ${{parameters.stageName}}_SAs_AustraliaSouthEast
      #    location: AustraliaSouthEast
      #    scope: group

      # AppInsights
      - template: ../jobs/deploy-appInsights.yml 
        parameters:
          jobDependsOn: ${{parameters.stageName}}_SAs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          vgs: ../vgs/global.yml
          resourceType: appInsights
          job: ${{parameters.stageName}}_AppIs_AustraliaEast
          location: AustraliaEast
          scope: group
      
      # Keyvaults
      - template: ../jobs/deploy-keyVaults.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_SAs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: keyVaults
          job: ${{parameters.stageName}}_KVs_AustraliaEast
          location: AustraliaEast
          scope: group
      #- template: ../jobs/deploy-keyVaults.yml
      #  parameters:
      #    jobDependsOn: ${{parameters.stageName}}_KVs_AustraliaEast
      #    serviceConnection: ${{parameters.serviceConnection}}
      #    hubserviceConnection: ${{parameters.serviceConnection}}
      #    environmentType: ${{parameters.environmentType}}
      #    vgs: ../vgs/global.yml
      #    resourceType: keyVaults
      #    job: ${{parameters.stageName}}_KVs_AustraliaSouthEast
      #    location: AustraliaSouthEast
      #    scope: group

      # Public IP Addresses
      - template: ../jobs/deploy-publicIpAddresses.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_KVs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: publicIpAddresses
          job: ${{parameters.stageName}}_PIPs_AustraliaEast
          location: AustraliaEast
          scope: group
      #- template: ../jobs/deploy-publicIpAddresses.yml
      #  parameters:
      #    jobDependsOn: ${{parameters.stageName}}_PIPs_AustraliaEast
      #    serviceConnection: ${{parameters.serviceConnection}}
      #    hubserviceConnection: ${{parameters.serviceConnection}}
      #    environmentType: ${{parameters.environmentType}}
      #    vgs: ../vgs/global.yml
      #    resourceType: publicIpAddresses
      #    job: ${{parameters.stageName}}_PIPs_AustraliaSouthEast
      #    location: AustraliaSouthEast
      #    scope: group

      # Virtual Networks
      - template: ../jobs/deploy-virtualNetworks.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_PIPs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: virtualNetworks
          job: ${{parameters.stageName}}_VNs_AustraliaEast
          location: AustraliaEast
          scope: group
      #- template: ../jobs/deploy-virtualNetworks.yml
      #  parameters:
      #    jobDependsOn: ${{parameters.stageName}}_VNs_AustraliaEast
      #    serviceConnection: ${{parameters.serviceConnection}}
      #    hubserviceConnection: ${{parameters.serviceConnection}}
      #    environmentType: ${{parameters.environmentType}}
      #    vgs: ../vgs/global.yml
      #    resourceType: virtualNetworks
      #    job: ${{parameters.stageName}}_VNs_AustraliaSouthEast
      #    location: AustraliaSouthEast
      #    scope: group

      # Private Endpoints
      - template: ../jobs/deploy-privateEndpoints.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_VNs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: privateEndpoints
          job: ${{parameters.stageName}}_PEPs_AustraliaEast
          location: AustraliaEast
          scope: group

      # Bastion
      - template: ../jobs/deploy-bastions.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_VNs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: bastionHosts
          job: ${{parameters.stageName}}_bastionHosts_ae_AustraliaEast
          location: AustraliaEast
          scope: group

      # VNET Gateways
      - template: ../jobs/deploy-virtualNetworkGateways.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_VNs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: virtualNetworkGateways
          job: ${{parameters.stageName}}_VN_Gateways_AustraliaEast
          location: AustraliaEast
          scope: group 

      # Private DNS Zones
      - template: ../jobs/deploy-privateDnsZones.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_VNs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: privateDNS
          job: ${{parameters.stageName}}_PrivateDnsZones_AustraliaEast
          location: AustraliaEast
          scope: group

      # Virtual Machines
      - template: ../jobs/deploy-virtualMachines.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_VNs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: virtualMachines
          job: ${{parameters.stageName}}_VMs_AustraliaEast
          location: AustraliaEast
          scope: group
      #- template: ../jobs/deploy-virtualMachines.yml
      #  parameters:
      #    jobDependsOn: ${{parameters.stageName}}_VNs_AustraliaSouthEast
      #    serviceConnection: ${{parameters.serviceConnection}}
      #    hubserviceConnection: ${{parameters.serviceConnection}}
      #    environmentType: ${{parameters.environmentType}}
      #    vgs: ../vgs/global.yml
      #    resourceType: virtualMachines
      #    job: ${{parameters.stageName}}_VMs_AustraliaSouthEast
      #    location: AustraliaSouthEast
      #    scope: group
      
      # Application Gateway
      - template: ../jobs/deploy-appGateways.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_SAs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: applicationGateway
          job: ${{parameters.stageName}}_AppGws_AustraliaEast
          location: AustraliaEast
          scope: group