parameters:
- name: environmentType
  type: string
- name: serviceConnection
  type: string
- name: hubServiceConnection
  type: string
- name: stageName
  type: string
stages:
  - stage: ${{parameters.stageName}}
    # do not run prod unless in master branch
    # only run if previous stage has completed successfully
    condition: and(or(not(eq('${{ parameters.environmentType }}', 'prod')), eq(variables['Build.SourceBranch'], 'refs/heads/master')),succeeded())
    jobs:
    # For Hub build the serviceConnection & hubServiceConnection are the same. This is not true for spoke

    # Resource Groups
      - template: ../jobs/deploy-resourceGroups.yml
        parameters:
          serviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: resourceGroups
          job: ${{parameters.stageName}}_RGs_AustraliaEast
          location: AustraliaEast
          scope: sub
      #- template: ../jobs/deploy-resourceGroups.yml
      #  parameters:
      #    serviceConnection: ${{parameters.serviceConnection}}
      #    environmentType: ${{parameters.environmentType}}
      #    vgs: ../vgs/global.yml
      #    resourceType: resourceGroups
      #    job: ${{parameters.stageName}}_RGs_AustraliaSouthEast
      #    location: AustraliaSouthEast
      #    scope: sub
      - template: ../jobs/deploy-actionGroups.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_RGs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: actionGroups
          job: ${{parameters.stageName}}_ActionGroups
          location: AustraliaEast
          scope: group

      # RoleAssignments
      # - template: ../jobs/deploy-roleAssignments.yml
      #   parameters:
      #     jobDependsOn: ${{parameters.stageName}}_RGs_AustraliaEast
      #     serviceConnection: ${{parameters.serviceConnection}}
      #     environmentType: ${{parameters.environmentType}}
      #     vgs: ../vgs/global.yml
      #     resourceType: roleAssignments
      #     job: ${{parameters.stageName}}_RoleAssignments_AustraliaEast
      #     location: AustraliaEast
      #     scope: group 
      # - template: ../jobs/deploy-roleAssignments.yml
      #   parameters:
      #     jobDependsOn: ${{parameters.stageName}}_RGs_AustraliaEast
      #     serviceConnection: ${{parameters.serviceConnection}}
      #     environmentType: ${{parameters.environmentType}}
      #     vgs: ../vgs/global.yml
      #     resourceType: roleAssignments
      #     job: ${{parameters.stageName}}_RoleAssignments_AustraliaSouthEast
      #     location: AustraliaSouthEast
      #     scope: group 
      
      # # Log Analytics
      - template: ../jobs/deploy-logAnalytics.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_RGs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: logAnalytics
          job: ${{parameters.stageName}}_WSs_AustraliaEast
          location: AustraliaEast
          scope: group

#       # # Data Collection Rule
      - template: ../jobs/deploy-dataCollectionRules.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_WSs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: dataCollectionRules
          job: ${{parameters.stageName}}_dataCollectionRules_AustraliaEast
          location: AustraliaEast
          scope: group 

      # #Storage Accounts
      - template: ../jobs/deploy-storageAccounts.yml 
        parameters:
          jobDependsOn: ${{parameters.stageName}}_WSs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: storageAccounts
          job: ${{parameters.stageName}}_SAs_AustraliaEast
          location: AustraliaEast
          scope: group
      #- template: ../jobs/deploy-storageAccounts.yml 
      #  parameters:
      #    jobDependsOn: ${{parameters.stageName}}_SAs_AustraliaEast
      #    serviceConnection: ${{parameters.serviceConnection}}
      #    hubserviceConnection: ${{parameters.serviceConnection}}
      #    environmentType: ${{parameters.environmentType}}
      #    vgs: ../vgs/global.yml
      #    resourceType: storageAccounts
      #    job: ${{parameters.stageName}}_SAs_AustraliaSouthEast
      #    location: AustraliaSouthEast
      #    scope: group

      # # Keyvaults
      - template: ../jobs/deploy-keyVaults.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_SAs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: keyVaults
          job: ${{parameters.stageName}}_KVs_AustraliaEast
          location: AustraliaEast
          scope: group
      #- template: ../jobs/deploy-keyVaults.yml
      #  parameters:
      #    jobDependsOn: ${{parameters.stageName}}_KVs_AustraliaEast
      #    serviceConnection: ${{parameters.serviceConnection}}
      #    hubserviceConnection: ${{parameters.serviceConnection}}
      #    environmentType: ${{parameters.environmentType}}
      #    vgs: ../vgs/global.yml
      #    resourceType: keyVaults
      #    job: ${{parameters.stageName}}_KVs_AustraliaSouthEast
      #    location: AustraliaSouthEast
      #    scope: group

      # Public IP Addresses
      - template: ../jobs/deploy-publicIpAddresses.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_KVs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: publicIpAddresses
          job: ${{parameters.stageName}}_PIPs_AustraliaEast
          location: AustraliaEast
          scope: group
      #- template: ../jobs/deploy-publicIpAddresses.yml
      #  parameters:
      #    jobDependsOn: ${{parameters.stageName}}_PIPs_AustraliaEast
      #    serviceConnection: ${{parameters.serviceConnection}}
      #    hubserviceConnection: ${{parameters.serviceConnection}}
      #    environmentType: ${{parameters.environmentType}}
      #    vgs: ../vgs/global.yml
      #    resourceType: publicIpAddresses
      #    job: ${{parameters.stageName}}_PIPs_AustraliaSouthEast
      #    location: AustraliaSouthEast
      #    scope: group

      # Virtual Networks
      - template: ../jobs/deploy-virtualNetworks.yml
        parameters:
          jobDependsOn: ${{parameters.stageName}}_PIPs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          hubserviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: virtualNetworks
          job: ${{parameters.stageName}}_VNs_AustraliaEast
          location: AustraliaEast
          scope: group       

      # ADDS
      - template: ../jobs/deploy-adds.yml 
        parameters:
          jobDependsOn: ${{parameters.stageName}}_VNs_AustraliaEast
          serviceConnection: ${{parameters.serviceConnection}}
          environmentType: ${{parameters.environmentType}}
          vgs: ../vgs/global.yml
          resourceType: adds
          job: ${{parameters.stageName}}_ADDSs_AustraliaEast
          location: AustraliaEast
          scope: group              