name: azure-tests
title: Azure InSpec Profile
maintainer: Andrew McGregor
copyright: a.mcgregor@avanoso.com
copyright_email: a.mcgregor@avanoso.com
license: Apache-2.0
summary: An InSpec Compliance Profile For Azure
version: 0.1.0
inspec_version: '>= 2.2.7'
depends:
- name: inspec-azure
  url: https://github.com/inspec/inspec-azure/archive/main.tar.gz
supports:
- platform: azure

